/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx_gpio_driver.h"

#include "stm32f407xx.h"
void delay()
{
 for(uint32_t i = 0; i<500000 ; i++);
}
int main(void)
{
	GPIO_Handle_t GpioLed;
	// 1) Select port
	GpioLed.pGPIOx = GPIOD;

	// 2) Configure pin using STRUCT MEMBERS (not whole struct)
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	/*If you want to use Output type as Push Pull use the below line of code*/
	//GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	/*If you want to use Output type as Open Drain use the below line of code*/
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;		//if you use it in the pull up mode led glows with a very less intensity and that is un-noticiable

	// Optional (but usually required if your driver expects it)
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_HS;
	GPIO_PClkCtrl(GPIOD, ENABLE);
	GPIO_Init(&GpioLed);
	while(1){
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
	delay();
	}
}
